[project]
name = "my-first-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openai>=2.15.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
